import { useState } from 'react';
import AdminMetricCard from '../../components/admin/AdminMetricCard';
import AdminSectionCard from '../../components/admin/AdminSectionCard';
import AdminToast from '../../components/admin/AdminToast';

const revenueTrend = [
  { month: 'Jan', value: 8, growth: '+6%' },
  { month: 'Feb', value: 12, growth: '+9%' },
  { month: 'Mar', value: 15, growth: '+11%' },
  { month: 'Apr', value: 18, growth: '+14%' },
  { month: 'May', value: 22, growth: '+17%' },
  { month: 'Jun', value: 25, growth: '+20%' },
];

const publicationTrend = [
  { month: 'Jan', value: 120, growth: '+8%' },
  { month: 'Feb', value: 180, growth: '+12%' },
  { month: 'Mar', value: 250, growth: '+15%' },
  { month: 'Apr', value: 320, growth: '+18%' },
  { month: 'May', value: 450, growth: '+22%' },
  { month: 'Jun', value: 600, growth: '+28%' },
];

const userOverview = {
  totalUsers: 1258,
  premiumUsers: 842,
  freeUsers: 416,
  adminUsers: 4,
};

const formatRevenue = (value: number) => `${value}M₫`;

const formatArticles = (value: number) => value.toLocaleString();

const AdminDashboardPage = () => {
  const [toast, setToast] = useState<string | null>(null);

  return (
    <div className="space-y-5">
      <AdminToast message={toast} onClose={() => setToast(null)} />

      <div>
        <h1 className="text-2xl font-bold tracking-tight text-gray-900">
          Admin Dashboard Overview
        </h1>
        <p className="mt-1 text-xs text-gray-500">
          Tổng quan số liệu bài báo, doanh thu và gói đăng ký của hệ thống.
        </p>
      </div>

      <div className="grid gap-5 lg:grid-cols-4">
        <AdminMetricCard
          label="TOTAL ARTICLES"
          value="144,528"
          helper="Articles stored in system"
          icon="📄"
          accent="blue"
        />

        <AdminMetricCard
          label="TOTAL REVENUE"
          value="24.8M₫"
          helper="Revenue from subscriptions"
          icon="₫"
          accent="green"
        />

        <AdminMetricCard
          label="TOTAL USERS"
          value="1,258"
          helper="Registered users in system"
          icon="👥"
          accent="slate"
        />

        <AdminMetricCard
          label="ACTIVE SUBSCRIPTIONS"
          value="842"
          helper="Premium Monthly & Yearly"
          icon="★"
          accent="orange"
        />
      </div>

      <div className="grid gap-5 xl:grid-cols-2">
        <AdminSectionCard
          title="Publication Trend"
          subtitle="Number of publications by month"
        >
          <div className="p-6">
            <div className="mb-5 flex items-end justify-between">
              <div>
                <p className="text-2xl font-bold text-gray-900">
                  {formatArticles(publicationTrend.reduce((sum, item) => sum + item.value, 0))}
                </p>
                <p className="text-xs font-semibold text-gray-500">
                  Publications in last 6 months
                </p>
              </div>

              <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">
                +28% peak growth
              </span>
            </div>

            <div className="flex h-64 items-end gap-4 rounded-xl bg-gray-50 p-5">
              {publicationTrend.map((item) => (
                <div
                  key={item.month}
                  className="group relative flex flex-1 flex-col items-center gap-3"
                >
                  <div
                    className="w-full max-w-[76px] rounded-t-xl bg-indigo-800 transition hover:opacity-80"
                    style={{ height: `${Math.min(item.value / 4, 220)}px` }}
                  />

                  <div className="pointer-events-none absolute bottom-16 z-10 hidden rounded-lg bg-gray-900 px-3 py-2 text-xs text-white shadow-lg group-hover:block">
                    <p className="font-bold">{item.month}</p>
                    <p>{formatArticles(item.value)} publications</p>
                    <p className="text-emerald-300">{item.growth} vs previous month</p>
                  </div>

                  <span className="text-xs font-semibold text-gray-500">
                    {item.month}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </AdminSectionCard>

        <AdminSectionCard
          title="Revenue Trend"
          subtitle="Revenue generated by subscription plans"
        >
          <div className="p-6">
            <div className="mb-5 flex items-end justify-between">
              <div>
                <p className="text-2xl font-bold text-gray-900">
                  {formatRevenue(revenueTrend.reduce((sum, item) => sum + item.value, 0))}
                </p>
                <p className="text-xs font-semibold text-gray-500">
                  Revenue in last 6 months
                </p>
              </div>

              <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">
                +20% peak growth
              </span>
            </div>

            <div className="flex h-64 items-end gap-4 rounded-xl bg-gray-50 p-5">
              {revenueTrend.map((item) => (
                <div
                  key={item.month}
                  className="group relative flex flex-1 flex-col items-center gap-3"
                >
                  <div
                    className="w-full max-w-[76px] rounded-t-xl bg-emerald-500 transition hover:opacity-80"
                    style={{ height: `${Math.min(item.value * 7, 220)}px` }}
                  />

                  <div className="pointer-events-none absolute bottom-16 z-10 hidden rounded-lg bg-gray-900 px-3 py-2 text-xs text-white shadow-lg group-hover:block">
                    <p className="font-bold">{item.month}</p>
                    <p>{formatRevenue(item.value)} revenue</p>
                    <p className="text-emerald-300">{item.growth} vs previous month</p>
                  </div>

                  <span className="text-xs font-semibold text-gray-500">
                    {item.month}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </AdminSectionCard>
      </div>

      <AdminSectionCard
        title="User Overview"
        subtitle="User account distribution by access level"
      >
        <div className="grid gap-6 p-6 md:grid-cols-[220px_1fr]">
          <div className="relative mx-auto flex h-44 w-44 items-center justify-center rounded-full bg-[conic-gradient(theme(colors.indigo.800)_0_67%,theme(colors.emerald.500)_67%_99%,theme(colors.orange.400)_99%_100%)]">
            <div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white shadow-inner">
              <span className="text-2xl font-bold text-gray-900">
                {userOverview.totalUsers.toLocaleString()}
              </span>
              <span className="text-xs font-semibold text-gray-500">
                Total Users
              </span>
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3">
              <span className="font-semibold text-gray-700">Total Users</span>
              <span className="font-bold text-gray-900">
                {userOverview.totalUsers.toLocaleString()}
              </span>
            </div>

            <div className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3">
              <span className="flex items-center gap-2 font-semibold text-gray-700">
                <span className="h-3 w-3 rounded-full bg-indigo-800" />
                Premium
              </span>
              <span className="font-bold text-gray-900">
                {userOverview.premiumUsers.toLocaleString()}
              </span>
            </div>

            <div className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3">
              <span className="flex items-center gap-2 font-semibold text-gray-700">
                <span className="h-3 w-3 rounded-full bg-emerald-500" />
                Free
              </span>
              <span className="font-bold text-gray-900">
                {userOverview.freeUsers.toLocaleString()}
              </span>
            </div>

            <div className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3">
              <span className="flex items-center gap-2 font-semibold text-gray-700">
                <span className="h-3 w-3 rounded-full bg-orange-400" />
                Admin
              </span>
              <span className="font-bold text-gray-900">
                {userOverview.adminUsers}
              </span>
            </div>
          </div>
        </div>
      </AdminSectionCard>

      <AdminSectionCard
        title="Subscription Distribution"
        subtitle="Current subscription plan allocation"
      >
        <div className="space-y-5 p-6">
          <div>
            <div className="mb-2 flex justify-between text-sm font-semibold">
              <span>Premium Monthly</span>
              <span>70%</span>
            </div>
            <div className="h-3 rounded-full bg-gray-100">
              <div className="h-3 rounded-full bg-indigo-800" style={{ width: '70%' }} />
            </div>
          </div>

          <div>
            <div className="mb-2 flex justify-between text-sm font-semibold">
              <span>Premium Yearly</span>
              <span>20%</span>
            </div>
            <div className="h-3 rounded-full bg-gray-100">
              <div className="h-3 rounded-full bg-emerald-500" style={{ width: '20%' }} />
            </div>
          </div>

          <div>
            <div className="mb-2 flex justify-between text-sm font-semibold">
              <span>Free Users</span>
              <span>10%</span>
            </div>
            <div className="h-3 rounded-full bg-gray-100">
              <div className="h-3 rounded-full bg-orange-400" style={{ width: '10%' }} />
            </div>
          </div>
        </div>
      </AdminSectionCard>
    </div>
  );
};

export default AdminDashboardPage;